positions:
    - name: "Community"
      desc: "Ensuring that the community is healthy."
      candidates:
          - name: "Tom Leese"

    - name: "Engineering"
      desc: "Oversees our engineering effort."
      candidates:
          - name: "Peter Law"
          - name: "Richard Barlow"

    - name: "Events"
      desc: "Ensures events get the organisation and attention that they need."
      candidates:
          - name: "Lilafisch"
          - name: "Sam Phippen"

    - name: "Public Interaction"
      desc: "Interaction with the press."
      candidates:
          - name: "Harry Cutts"

    - name: "School interaction, mentoring and support"
      desc: "Communications with schools and students, and mentor organisation."
      candidates:
          - name: "Jeremy Morse"
          - name: "Jon Bartlett"

    - name: "Sponsor Interaction"
      desc: "Ensuring we have funds."
      candidates:
          - name: "Andrew Busse"
          - name: "Rob Spanton"
