positions:
#    - name: "Community"
#      desc: "Ensuring that the community is healthy."
#      candidates:
#          - name: "Andy Cottrell"

    - name: "Engineering"
      desc: "Oversees our engineering effort."
      candidates:
          - name: "Richard Barlow"

    - name: "Events"
      desc: "Ensures events get the organisation and attention that they need."
      candidates:
          - name: "Alistair Lynn"
          - name: "Sam Phippen"

    - name: "Public Interaction"
      desc: "Interaction with the press."
      candidates:
          - name: "Andy Cottrell"

    - name: "School interaction, mentoring and support"
      desc: "Communications with schools and students, and mentor organisation."
      candidates:
          - name: "Jeremy Morse"

    - name: "Sponsor Interaction"
      desc: "Ensuring we have funds."
      candidates:
          - name: "Rob Spanton"
